{% set name = "bw2analyzer" %}
{% set version = "0.9.4" %}
{% set sha256 = "10500d47b85cd6c4ffe47ca983fd48ca6e87b04aca1fea39c5114334ea4b820a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - bw2calc
    - bw2data
    - matplotlib-base
    - numpy
    - pyprind
    - stats_arrays
    - eight
    - python
    - requests
    - scipy

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/brightway-lca/brightway2-analyzer
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Interpretation and other tools for Brightway2 LCA framework'
  license_family: BSD
